const mongoose = require('mongoose');
require('dotenv').config();
const Package = require('./models/Package');

const MONGO_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/wanderlust';

const packages = [
  {
    title: 'Magical Bali Escape',
    slug: 'magical-bali-escape',
    destination: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    description: 'Immerse yourself in the enchanting beauty of Bali with our curated 7-day escape. From ancient temples and terraced rice paddies to pristine beaches and vibrant nightlife, experience the Island of the Gods like never before.',
    highlights: ['Visit Uluwatu Temple at sunset', 'Tegallalang Rice Terraces trek', 'Snorkeling in Nusa Penida', 'Traditional Balinese cooking class', 'Ubud Monkey Forest exploration'],
    duration: '7 Days / 6 Nights',
    price: 1299,
    originalPrice: 1599,
    rating: 4.8,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600',
      'https://images.unsplash.com/photo-1573790387438-4da905039392?w=600',
      'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?w=600',
    ],
    included: ['Airport transfers', '4-star resort accommodation', 'Daily breakfast', 'Guided tours', 'Snorkeling gear', 'Cooking class'],
    excluded: ['International flights', 'Travel insurance', 'Personal expenses', 'Lunch & dinner'],
    itinerary: [
      { day: 1, title: 'Arrival & Welcome', description: 'Airport pickup, resort check-in, welcome dinner with traditional dance performance.' },
      { day: 2, title: 'Ubud Cultural Tour', description: 'Visit the Sacred Monkey Forest, Tegallalang Rice Terraces, and local artisan villages.' },
      { day: 3, title: 'Temples & Waterfalls', description: 'Explore Tirta Empul water temple and Tegenungan Waterfall.' },
      { day: 4, title: 'Nusa Penida Day Trip', description: 'Boat trip to Nusa Penida. Visit Kelingking Beach, snorkel with manta rays.' },
      { day: 5, title: 'Cooking & Spa', description: 'Morning Balinese cooking class, afternoon spa treatment at the resort.' },
      { day: 6, title: 'Uluwatu & Beach', description: 'Visit Uluwatu Temple for sunset Kecak dance, dinner at Jimbaran Bay.' },
      { day: 7, title: 'Departure', description: 'Leisure morning, souvenir shopping, airport transfer.' },
    ],
    category: 'cultural',
    featured: true,
    maxGroupSize: 16,
    difficulty: 'easy',
  },
  {
    title: 'Swiss Alps Adventure',
    slug: 'swiss-alps-adventure',
    destination: 'Interlaken',
    country: 'Switzerland',
    continent: 'Europe',
    description: 'Conquer the majestic Swiss Alps on this thrilling 8-day adventure. Hike through pristine alpine meadows, cruise crystal-clear lakes, and ride the famous Jungfrau railway to the Top of Europe.',
    highlights: ['Jungfraujoch railway experience', 'Paragliding over Interlaken', 'Lake Thun boat cruise', 'Grindelwald First cliff walk', 'Swiss chocolate workshop'],
    duration: '8 Days / 7 Nights',
    price: 2499,
    originalPrice: 2999,
    rating: 4.9,
    reviewCount: 187,
    image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=600',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=600',
    ],
    included: ['Mountain lodge accommodation', 'Daily breakfast & dinner', 'Jungfrau rail pass', 'Guided hikes', 'Paragliding session', 'Swiss Travel Pass'],
    excluded: ['International flights', 'Travel insurance', 'Lunch', 'Personal equipment'],
    itinerary: [
      { day: 1, title: 'Arrival in Zurich', description: 'Airport transfer to Interlaken, evening orientation walk.' },
      { day: 2, title: 'Jungfraujoch Excursion', description: 'Train to the Top of Europe at 3,454m. Visit Ice Palace and Sphinx Observatory.' },
      { day: 3, title: 'Lake Thun & Thun Town', description: 'Morning boat cruise, explore medieval Thun Castle and old town.' },
      { day: 4, title: 'Grindelwald First', description: 'Cable car to First, cliff walk, and mountain cart descent.' },
      { day: 5, title: 'Paragliding Day', description: 'Tandem paragliding over Interlaken, free afternoon.' },
      { day: 6, title: 'Lauterbrunnen Valley', description: 'Hike through the valley of 72 waterfalls, visit Trummelbach Falls.' },
      { day: 7, title: 'Chocolate & Cheese', description: 'Swiss chocolate workshop, visit a traditional alpine cheese dairy.' },
      { day: 8, title: 'Departure', description: 'Morning at leisure, transfer to Zurich airport.' },
    ],
    category: 'adventure',
    featured: true,
    maxGroupSize: 12,
    difficulty: 'moderate',
  },
  {
    title: 'Santorini Dream Getaway',
    slug: 'santorini-dream-getaway',
    destination: 'Santorini',
    country: 'Greece',
    continent: 'Europe',
    description: 'Live the dream in the iconic white-washed villages of Santorini. Watch legendary sunsets over the caldera, sail around volcanic islands, and savor world-class Mediterranean cuisine.',
    highlights: ['Oia sunset experience', 'Caldera sailing cruise', 'Wine tasting tour', 'Red Beach visit', 'Ancient Akrotiri ruins'],
    duration: '6 Days / 5 Nights',
    price: 1899,
    originalPrice: 2299,
    rating: 4.7,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=600',
      'https://images.unsplash.com/photo-1571406761478-4a0afa116528?w=600',
      'https://images.unsplash.com/photo-1604580864964-0462f5d5b1a8?w=600',
    ],
    included: ['Cave hotel accommodation', 'Daily breakfast', 'Catamaran cruise with BBQ', 'Wine tour', 'Airport transfers', 'Guided walking tours'],
    excluded: ['International flights', 'Travel insurance', 'Lunch & most dinners', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Santorini', description: 'Airport pickup, check into cave hotel in Oia, welcome cocktail.' },
      { day: 2, title: 'Oia & Fira Exploration', description: 'Walking tour of Oia, visit Fira town, sunset at the castle.' },
      { day: 3, title: 'Caldera Sailing', description: 'Full-day catamaran cruise around the caldera, hot springs, BBQ lunch.' },
      { day: 4, title: 'Wine & History', description: 'Visit Akrotiri archaeological site, afternoon wine tasting at local vineyards.' },
      { day: 5, title: 'Beaches & Leisure', description: 'Visit Red Beach and Perissa Black Sand Beach, evening farewell dinner.' },
      { day: 6, title: 'Departure', description: 'Leisure morning, airport transfer.' },
    ],
    category: 'honeymoon',
    featured: true,
    maxGroupSize: 10,
    difficulty: 'easy',
  },
  {
    title: 'African Safari Expedition',
    slug: 'african-safari-expedition',
    destination: 'Serengeti & Ngorongoro',
    country: 'Tanzania',
    continent: 'Africa',
    description: 'Witness the raw beauty of the African wilderness on this 10-day safari expedition. Track the Big Five across the Serengeti, descend into the Ngorongoro Crater, and experience authentic Maasai culture.',
    highlights: ['Big Five game drives', 'Great Migration viewing', 'Ngorongoro Crater descent', 'Maasai village visit', 'Hot air balloon safari', 'Stargazing in the bush'],
    duration: '10 Days / 9 Nights',
    price: 3999,
    originalPrice: 4799,
    rating: 4.9,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=600',
      'https://images.unsplash.com/photo-1549366021-9f761d450615?w=600',
      'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=600',
    ],
    included: ['Luxury tented camp accommodation', 'All meals on safari', 'Expert safari guide', '4x4 Land Cruiser', 'Park entrance fees', 'Bush breakfast'],
    excluded: ['International flights', 'Travel insurance', 'Hot air balloon (optional)', 'Gratuities', 'Visa fees'],
    itinerary: [
      { day: 1, title: 'Arrival in Arusha', description: 'Airport pickup, overnight at lodge, safari briefing.' },
      { day: 2, title: 'Tarangire National Park', description: 'Drive to Tarangire, famous for its elephant herds and baobab trees.' },
      { day: 3, title: 'Lake Manyara', description: 'Game drive in Lake Manyara, known for tree-climbing lions.' },
      { day: 4, title: 'Ngorongoro Crater', description: 'Descend into the worlds largest intact caldera for a full-day game drive.' },
      { day: 5, title: 'Maasai Cultural Visit', description: 'Visit a Maasai village, learn about their traditions and way of life.' },
      { day: 6, title: 'Central Serengeti', description: 'Drive to the Serengeti, afternoon game drive in the Seronera area.' },
      { day: 7, title: 'Serengeti Full Day', description: 'Full-day game drive tracking big cats and the Great Migration herds.' },
      { day: 8, title: 'Northern Serengeti', description: 'Drive to the Mara River area, watch wildebeest crossings (seasonal).' },
      { day: 9, title: 'Balloon Safari', description: 'Optional hot air balloon safari at dawn, afternoon game drive.' },
      { day: 10, title: 'Departure', description: 'Morning bush walk, fly back to Arusha, departure.' },
    ],
    category: 'wildlife',
    featured: true,
    maxGroupSize: 8,
    difficulty: 'moderate',
  },
  {
    title: 'Maldives Luxury Retreat',
    slug: 'maldives-luxury-retreat',
    destination: 'Malé Atoll',
    country: 'Maldives',
    continent: 'Asia',
    description: 'Indulge in ultimate luxury at an overwater villa resort in the Maldives. Crystal-clear turquoise waters, pristine white sand beaches, and world-class diving make this the perfect tropical paradise escape.',
    highlights: ['Overwater villa stay', 'Sunset dolphin cruise', 'Scuba diving & snorkeling', 'Private beach dinner', 'Underwater restaurant experience', 'Spa overwater treatment'],
    duration: '6 Days / 5 Nights',
    price: 4499,
    originalPrice: 5499,
    rating: 4.9,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600',
      'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=600',
      'https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=600',
    ],
    included: ['Overwater villa accommodation', 'Full board (all meals)', 'Speedboat transfers', 'Sunset dolphin cruise', 'Snorkeling equipment', 'One spa treatment'],
    excluded: ['International flights', 'Travel insurance', 'Scuba diving courses', 'Premium drinks', 'Gratuities'],
    itinerary: [
      { day: 1, title: 'Paradise Arrival', description: 'Speedboat transfer to resort, overwater villa check-in, welcome cocktail.' },
      { day: 2, title: 'Ocean Adventures', description: 'Morning snorkeling at house reef, afternoon sunset dolphin cruise.' },
      { day: 3, title: 'Island Hopping', description: 'Visit local islands, experience Maldivian culture, sandbank picnic.' },
      { day: 4, title: 'Dive & Spa', description: 'Morning scuba diving session, afternoon overwater spa treatment.' },
      { day: 5, title: 'Leisure & Romance', description: 'Free day at the resort, private beach dinner under the stars.' },
      { day: 6, title: 'Departure', description: 'Final swim, breakfast, speedboat transfer to airport.' },
    ],
    category: 'luxury',
    featured: true,
    maxGroupSize: 6,
    difficulty: 'easy',
  },
  {
    title: 'Machu Picchu Trek',
    slug: 'machu-picchu-trek',
    destination: 'Cusco & Sacred Valley',
    country: 'Peru',
    continent: 'South America',
    description: 'Follow in the footsteps of the Incas on this epic trek to Machu Picchu. Journey through the Sacred Valley, hike the legendary Inca Trail, and witness the sunrise over one of the New Seven Wonders of the World.',
    highlights: ['Classic Inca Trail trek', 'Machu Picchu sunrise', 'Sacred Valley tour', 'Cusco city exploration', 'Rainbow Mountain hike', 'Traditional Pachamanca feast'],
    duration: '9 Days / 8 Nights',
    price: 2199,
    originalPrice: 2699,
    rating: 4.8,
    reviewCount: 267,
    image: 'https://images.unsplash.com/photo-1587595431973-160d0d163571?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600',
      'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=600',
      'https://images.unsplash.com/photo-1415804941882-1f16f8dc5c6f?w=600',
    ],
    included: ['Hotel & camping accommodation', 'All meals on trek', 'Expert Inca Trail guide', 'Porters & equipment', 'Train tickets', 'Entrance fees'],
    excluded: ['International flights', 'Travel insurance', 'Sleeping bag rental', 'Tips for porters', 'Personal snacks'],
    itinerary: [
      { day: 1, title: 'Arrival in Cusco', description: 'Airport pickup, acclimatization day, city walking tour.' },
      { day: 2, title: 'Sacred Valley', description: 'Visit Pisac ruins and market, Ollantaytambo fortress.' },
      { day: 3, title: 'Inca Trail Day 1', description: 'Begin the trek at Km 82, hike to Wayllabamba campsite.' },
      { day: 4, title: 'Inca Trail Day 2', description: 'Cross Dead Womans Pass (4,215m), the highest point of the trail.' },
      { day: 5, title: 'Inca Trail Day 3', description: 'Explore Inca ruins along the trail, camp at Wiñay Wayna.' },
      { day: 6, title: 'Machu Picchu', description: 'Pre-dawn hike to Sun Gate, guided tour of Machu Picchu.' },
      { day: 7, title: 'Rainbow Mountain', description: 'Day trip to Vinicunca Rainbow Mountain (optional, weather permitting).' },
      { day: 8, title: 'Cusco Free Day', description: 'Explore Cusco at leisure, San Pedro Market, evening farewell dinner.' },
      { day: 9, title: 'Departure', description: 'Airport transfer, departure.' },
    ],
    category: 'adventure',
    featured: false,
    maxGroupSize: 14,
    difficulty: 'challenging',
  },
  {
    title: 'Japanese Culture Journey',
    slug: 'japanese-culture-journey',
    destination: 'Tokyo, Kyoto & Osaka',
    country: 'Japan',
    continent: 'Asia',
    description: 'Discover the fascinating blend of ancient tradition and cutting-edge modernity in Japan. From neon-lit Tokyo streets to serene Kyoto temples, experience the rich tapestry of Japanese culture, cuisine, and hospitality.',
    highlights: ['Tokyo Shibuya & Akihabara', 'Kyoto bamboo forest & geisha district', 'Mount Fuji day trip', 'Traditional ryokan stay', 'Osaka street food tour', 'Bullet train experience'],
    duration: '10 Days / 9 Nights',
    price: 3299,
    originalPrice: 3899,
    rating: 4.8,
    reviewCount: 203,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600',
      'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=600',
      'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=600',
    ],
    included: ['Hotel & ryokan accommodation', 'Daily breakfast', '7-day Japan Rail Pass', 'Guided city tours', 'Cooking class', 'Tea ceremony experience'],
    excluded: ['International flights', 'Travel insurance', 'Most lunches & dinners', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Welcome to Tokyo', description: 'Airport pickup, check-in, evening walk through Shinjuku.' },
      { day: 2, title: 'Tokyo Highlights', description: 'Meiji Shrine, Harajuku, Shibuya Crossing, Akihabara.' },
      { day: 3, title: 'Mount Fuji Day Trip', description: 'Bullet train to Hakone, Lake Ashi cruise, views of Mount Fuji.' },
      { day: 4, title: 'Tokyo to Kyoto', description: 'Shinkansen to Kyoto, afternoon visit to Fushimi Inari shrine.' },
      { day: 5, title: 'Kyoto Temples', description: 'Kinkaku-ji, Arashiyama Bamboo Grove, traditional tea ceremony.' },
      { day: 6, title: 'Kyoto & Nara', description: 'Day trip to Nara deer park, evening in Gion geisha district.' },
      { day: 7, title: 'Ryokan Experience', description: 'Stay in a traditional Japanese inn with onsen hot spring bath.' },
      { day: 8, title: 'Kyoto to Osaka', description: 'Train to Osaka, Osaka Castle, Dotonbori street food tour.' },
      { day: 9, title: 'Osaka Free Day', description: 'Explore Osaka at leisure, cooking class, farewell dinner.' },
      { day: 10, title: 'Departure', description: 'Transfer to Kansai International Airport.' },
    ],
    category: 'cultural',
    featured: false,
    maxGroupSize: 14,
    difficulty: 'easy',
  },
  {
    title: 'Costa Rica Eco-Adventure',
    slug: 'costa-rica-eco-adventure',
    destination: 'San José, Arenal & Manuel Antonio',
    country: 'Costa Rica',
    continent: 'North America',
    description: 'Experience the Pura Vida lifestyle in Costa Rica! From misty cloud forests and active volcanoes to tropical beaches and world-class surfing, this eco-adventure showcases the incredible biodiversity of Central America.',
    highlights: ['Arenal Volcano hot springs', 'Monteverde cloud forest zip-lining', 'Manuel Antonio beach & wildlife', 'White water rafting', 'Jungle night walk', 'Coffee plantation tour'],
    duration: '8 Days / 7 Nights',
    price: 1799,
    originalPrice: 2199,
    rating: 4.7,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1518259102261-b57d45c39e49?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1580086319619-3ed498161c77?w=600',
      'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=600',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600',
    ],
    included: ['Eco-lodge accommodation', 'Daily breakfast', 'All activities listed', 'Bilingual guide', 'Internal transfers', 'National park fees'],
    excluded: ['International flights', 'Travel insurance', 'Lunch & dinner', 'Optional activities'],
    itinerary: [
      { day: 1, title: 'Arrival in San José', description: 'Airport pickup, transfer to hotel, welcome briefing.' },
      { day: 2, title: 'Coffee Country', description: 'Visit a coffee plantation, transfer to Arenal Volcano area.' },
      { day: 3, title: 'Arenal Adventures', description: 'Hanging bridges walk, hot springs evening relaxation.' },
      { day: 4, title: 'White Water Rafting', description: 'Morning rafting on Pacuare River, afternoon at leisure.' },
      { day: 5, title: 'Monteverde Cloud Forest', description: 'Transfer to Monteverde, zip-line canopy tour, night walk.' },
      { day: 6, title: 'Manuel Antonio', description: 'Drive to the Pacific coast, beach time, sunset viewing.' },
      { day: 7, title: 'National Park & Wildlife', description: 'Guided tour of Manuel Antonio National Park, spot monkeys and sloths.' },
      { day: 8, title: 'Departure', description: 'Morning beach time, transfer to San José airport.' },
    ],
    category: 'adventure',
    featured: false,
    maxGroupSize: 16,
    difficulty: 'moderate',
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');
    await Package.deleteMany({});
    console.log('Cleared existing packages');
    const result = await Package.insertMany(packages);
    console.log(`Seeded ${result.length} travel packages`);
    await mongoose.disconnect();
    console.log('Done!');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
}

seed();
